#!/bin/sh
[ $PASS = "**NULL**" ] && PASS=`pwgen -s 12 1`
cat > /etc/shadowsocks/config.json << EOF
{
	"server":"0.0.0.0",
	"server_port":8388,
	"local_port":1080,
	"password":"${PASS}",
	"timeout":600,
	"method":"aes-256-cfb"
}
EOF
echo "=> The Password is ${PASS}"
ssserver -c /etc/shadowsocks/config.json
